version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: my_new_project2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_new_project2_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_new_project2_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_new_project2_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/my_new_project2
      dockerfile: Dockerfile
    container_name: my_new_project2_frontend
    restart: always
    volumes:
      - ./frontend/my_new_project2:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
